### ISSUE TITLE
[BUG] Need to ensure that `-r` and `-v` are mutually exclusive

### ISSUE THREAD

**Issue by pcansler** [plus3it/AMIgen8#14] opened 2020-04-29 21:38 UTC
**Describe the bug**
DiskSetup.sh doesn't work

**Severity**
- [X] Completely Broken (No work-around evident)
- [ ] Severely Broken (Work-around possible but difficult)
- [ ] Moderately Broken (Trivial work-around)
- [ ] Nuisance (Functions but untrapped errors can slip through)

**To Reproduce**

The script executes but doesn't actually do anything.

```
[root@ip-10-24-0-29 AMIgen8]# bash -x ./DiskSetup.sh -B 2 -d /dev/xvdc -f xfs -p /:root_lv:1,/tmp:tmp_lv:2,/usr:usr_lv:6,/var:var_lv:4,swap:swaplv:4,/opt:opt_lv:5,/home:home_lv:5,/usr/local/packages:usr_localp_lv:6,/var/log:varlog_lv:4,/var/tmp:vartmp_lv:2,/var/log/audit:varaudit_lv:2,/var/cache/yum:cache_lv:4 -r root_disk -v VolGroup00
+ set -eu -o pipefail
++ basename ./DiskSetup.sh
+ PROGNAME=DiskSetup.sh
+ BOOTDEVSZ=500m
+ DEBUG=UNDEF
+ FSTYPE=xfs
++ tty -s
+ [[ '' -eq 0 ]]
+ [[ UNDEF == \U\N\D\E\F ]]
+ DEBUG=true
++ getopt -o b:B:d:f:hp:r:v: --long bootlabel:,boot-size:,disk:,fstype:,help,partition-string:,rootlabel:,vgname: -n DiskSetup.sh -- -B 2 -d /dev/xvdc -f xfs -p /:root_lv:1,/tmp:tmp_lv:2,/usr:usr_lv:6,/var:var_lv:4,swap:swaplv:4,/opt:opt_lv:5,/home:home_lv:5,/usr/local/packages:usr_localp_lv:6,/var/log:varlog_lv:4,/var/tmp:vartmp_lv:2,/var/log/audit:varaudit_lv:2,/var/cache/yum:cache_lv:4 -r root_disk -v VolGroup00
+ OPTIONBUFR=' -B '\''2'\'' -d '\''/dev/xvdc'\'' -f '\''xfs'\'' -p '\''/:root_lv:1,/tmp:tmp_lv:2,/usr:usr_lv:6,/var:var_lv:4,swap:swaplv:4,/opt:opt_lv:5,/home:home_lv:5,/usr/local/packages:usr_localp_lv:6,/var/log:varlog_lv:4,/var/tmp:vartmp_lv:2,/var/log/audit:varaudit_lv:2,/var/cache/yum:cache_lv:4'\'' -r '\''root_disk'\'' -v '\''VolGroup00'\'' --'
+ eval set -- ' -B '\''2'\'' -d '\''/dev/xvdc'\'' -f '\''xfs'\'' -p '\''/:root_lv:1,/tmp:tmp_lv:2,/usr:usr_lv:6,/var:var_lv:4,swap:swaplv:4,/opt:opt_lv:5,/home:home_lv:5,/usr/local/packages:usr_localp_lv:6,/var/log:varlog_lv:4,/var/tmp:vartmp_lv:2,/var/log/audit:varaudit_lv:2,/var/cache/yum:cache_lv:4'\'' -r '\''root_disk'\'' -v '\''VolGroup00'\'' --'
++ set -- -B 2 -d /dev/xvdc -f xfs -p /:root_lv:1,/tmp:tmp_lv:2,/usr:usr_lv:6,/var:var_lv:4,swap:swaplv:4,/opt:opt_lv:5,/home:home_lv:5,/usr/local/packages:usr_localp_lv:6,/var/log:varlog_lv:4,/var/tmp:vartmp_lv:2,/var/log/audit:varaudit_lv:2,/var/cache/yum:cache_lv:4 -r root_disk -v VolGroup00 --
+ true
+ case "$1" in
+ case "$2" in
+ BOOTDEVSZ=2
+ shift 2
+ true
+ case "$1" in
+ case "$2" in
+ CHROOTDEV=/dev/xvdc
+ shift 2
+ true
+ case "$1" in
+ case "$2" in
+ FSTYPE=xfs
+ MKFSFORCEOPT=-f
+ shift 2
+ true
+ case "$1" in
+ case "$2" in
+ GEOMETRYSTRING=/:root_lv:1,/tmp:tmp_lv:2,/usr:usr_lv:6,/var:var_lv:4,swap:swaplv:4,/opt:opt_lv:5,/home:home_lv:5,/usr/local/packages:usr_localp_lv:6,/var/log:varlog_lv:4,/var/tmp:vartmp_lv:2,/var/log/audit:varaudit_lv:2,/var/cache/yum:cache_lv:4
+ shift 2
+ true
+ case "$1" in
+ case "$2" in
+ ROOTLABEL=root_disk
+ shift 2
+ true
+ case "$1" in
+ case "$2" in
+ VGNAME=VolGroup00
+ shift 2
+ true
+ case "$1" in
+ shift
+ break
+ [[ 0 != 0 ]]
+ [[ -z xxx ]]
+ [[ -n xxx ]]
+ [[ -z xxx ]]
```

**Comment by ferricoxide** [comment] 2020-04-30 04:04
I'll check it out next time I'm working on this project, but a couple oddities in your invocation:

* The `-B 2` specification would result in a two-sector (1KiB) boot-bock:

    ~~~
    Number  Start   End     Size    File system  Name     Flags
     1      1049kB  2097kB  1049kB               primary  bios_grub
    ~~~

   Which I don't know is big enough to host a GRUB2 record.

* The `-r` and `-v` flags were intended to be mutually exclusive – the latter for creating an LVM'ed installation-target and the latter for creating a non-LVM'ed installation-target. While it probably shouldn't cause a problem, I probably need to actually enforce that.
* The partitioning-description (`-p`) seems really odd. Are you really looking to create:
    * 1GiB LV named `root_lv` mounted at `/`
    * 2GiB LV named `tmp_lv` mounted at `/tmp`
    * 6GiB LV named `usr_lv` mounted at `/usr`
    * 4GiB LV named `var_lv` mounted at `/var`
    * 4GiB LV named `swaplv` mounted at `swap`
    * 5GiB LV named `opt_lv` mounted at `/opt`
    * 5GiB LV named `home_lv` mounted at `/home`
    * 6GiB LV named `usr_localp_lv` mounted at `/usr/local/packages`
    * 4GiB LV named `varlog_lv` mounted at `/var/log`
    * 2GiB LV named `vartmp_lv` mounted at `/var/tmp`
    * 2GiB LV named `varaudit_lv` mounted at `/var/log/audit`
    * 4GiB LV named `cache_lv` mounted at `/var/cache/yum`

    (And is your target EBS at least 45GiB in size)?
* It's worth noting that, unless you pass the "/tmp as tmpfs" inhibition-flag to the post-configuration script, the requested `tmp_lv` will ultimately end up as wasted space.

**Comment by ferricoxide** [comment] 2020-04-30 04:09
Actually, found the problem:

~~~
# Determine how we're formatting the disk
if [[ -z ${ROOTLABEL+xxx} ]] && [[ -n ${VGNAME+xxx} ]]
then
   CarveLVM
elif [[ -n ${ROOTLABEL+xxx} ]] && [[ -z ${VGNAME+xxx} ]]
then
   CarveBare
fi
~~~

Because you specified _both_ the `-r` and `-v` flags, there's no match found in this logic-block.

* Had you specified _just_ the `-v` flag, it would have called he `CarveLVM` function
* Had you specified _just_ the `-r` flag, it would have called the `CarveBare` function.

So, the primary problem here is that I didn't have an error condition for specifying both flags.

For now, the fix would be to remove the `-r` from your invocation.

**Comment by pcansler** [comment] 2020-04-30 12:30
I saw that in your code and thought they were mutually exclusive too, but without -r flag the script failed with:

./DiskSetup.sh: line 127: PARTPRE: unbound variable

However I think the -B 2 was the bigger issue as I intended /boot to be 2G.  I ran it this morning with -B 2000 and without the -r flag and the script ran through successfully.

Thanks for the quick response and sharing your work!

**Comment by ferricoxide** [comment] 2020-04-30 18:32
Note: once the current PR is merged, the script will error-exit on use of conflicting `-r`/`-v` flags:

~~~
./DiskSetup.sh -B 5m -d /dev/xvdx -f xfs \
  -p /:root_lv:1,/tmp:tmp_lv:2,/usr:usr_lv:6,/var:var_lv:4,swap:swaplv:4,/opt:opt_lv:5,/home:home_lv:5,/usr/local/packages:usr_localp_lv:6,/var/log:varlog_lv:4,/var/tmp:vartmp_lv:2,/var/log/audit:varaudit_lv:2,/var/cache/yum:cache_lv:4 \
  -r root_disk -v VolGroup00
<10>Apr 30 18:09:55 DiskSetup.sh[2135]: The '-r'/'--rootlabel' and '-v'/'--vgname' flag-options are mutually-exclusive. Exiting.
~~~

Also updated the README for DiskSetup to make a note about the mutually-exclusive nature of the two flags.

As to the UNBOUND-var error you noted, when I execute:

~~~
./DiskSetup.sh -B 5m -d /dev/xvdx -f xfs -p /:root_lv:1,/tmp:tmp_lv:2,/usr:usr_lv:6,/var:var_lv:4,swap:swaplv:4,/opt:opt_lv:5,/home:home_lv:5,/usr/local/packages:usr_localp_lv:6,/var/log:varlog_lv:4,/var/tmp:vartmp_lv:2,/var/log/audit:varaudit_lv:2,/var/cache/yum:cache_lv:4 -v VolGroup00
~~~

I'm not seeing that error. Is there something I'm missing when trying to reproduce? The shell-linters in our CI hadn't picked it up, and, it's generally been good about flagging those? Looking at the relevant code-block (note: line numbers are skewed in my fork/branch due to adding further error-detection):

~~~
    123    # Let's only attempt this if we're a secondary EBS
    124    if [[ ${CHROOTDEV} == /dev/xvda ]] || [[ ${CHROOTDEV} == /dev/nvme0n1 ]]
    125    then
    126       err_exit "Skipping explicit pvcreate opertion... " NONE
    127    else
    128       err_exit "Creating LVM2 PV ${CHROOTDEV}${PARTPRE}2..." NONE
    129       pvcreate "${CHROOTDEV}${PARTPRE}2" || \
    130         err_exit "PV creation failed. Aborting!"
    131    fi
~~~

That _should_ only happen if you failed to specify `-d`/`--disk` ...and I think that, as part of the PR fixing the failure to err-exit on mutually-exclusive flags, I added logic to not only exit on failure to specify -d`/`--disk` but prevent a scenario where `${PARTPRE}` is unbound. At any rate, if I execute without specifying `-d`/`--disk`, I now get the error-exit:

~~~
<10>Apr 30 18:19:00 DiskSetup.sh[2528]: Failed to specify partitioning-target. Aborting
~~~

And no unbound-vars error.

**Comment by ferricoxide** [comment] 2020-04-30 18:54
Alright, looks like get a working system from that partition-string (when using soon to be merged code):

~~~
[maintuser@ip-172-31-77-219 ~]$ df -PH
Filesystem                            Size  Used Avail Use% Mounted on
devtmpfs                              904M     0  904M   0% /dev
tmpfs                                 940M     0  940M   0% /dev/shm
tmpfs                                 940M  451k  939M   1% /run
tmpfs                                 940M     0  940M   0% /sys/fs/cgroup
/dev/mapper/VolGroup00-root_lv        1.1G  244M  821M  23% /
/dev/mapper/VolGroup00-usr_lv         6.5G  1.6G  4.9G  24% /usr
/dev/mapper/VolGroup00-home_lv        5.4G   72M  5.3G   2% /home
/dev/mapper/VolGroup00-usr_localp_lv  6.5G   79M  6.4G   2% /usr/local/packages
/dev/mapper/VolGroup00-tmp_lv         2.2G   49M  2.1G   3% /tmp
/dev/mapper/VolGroup00-opt_lv         5.4G  283M  5.1G   6% /opt
/dev/mapper/VolGroup00-var_lv         4.3G  207M  4.1G   5% /var
/dev/mapper/VolGroup00-cache_lv       4.3G   64M  4.3G   2% /var/cache/yum
/dev/mapper/VolGroup00-varlog_lv      4.3G   82M  4.3G   2% /var/log
/dev/mapper/VolGroup00-vartmp_lv      2.2G   49M  2.1G   3% /var/tmp
/dev/mapper/VolGroup00-varaudit_lv    2.2G   49M  2.1G   3% /var/log/audit
tmpfs                                 188M     0  188M   0% /run/user/1000
[maintuser@ip-172-31-77-219 ~]$ cat /proc/sys/crypto/fips_enabled
1
~~~

**Closed** 2020-04-30 19:05 UTC
Labels: bug
